# src/rura_penthe/optimizer/base.py
import subprocess
from pathlib import Path
from abc import ABC, abstractmethod
from typing import List, Dict, Any

class TokenOptimizer(ABC):
    """
    Abstract Base Class defining the payload contract for the middleware.
    """
    
    @abstractmethod
    def optimize_payload(self, messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Takes the heavy messages list generated by spec-kit and compresses it.
        """
        pass

class ContextCompressor(ABC):
    """
    Compresses specific parts of the message (e.g., removing redundant CoT).
    """
    
    @abstractmethod
    def compress(self, content: str) -> str:
        """
        Strips redundant instructions.
        """
        pass

class InterceptorMiddleware:
    """
    Orchestrates the LLMLingua compression pipeline natively from specify-cli,
    specifically designed to intercept large string payloads (Markdown body text) 
    before agent file generation.
    """
    def __init__(self, project_root: Path):
        self.project_root = Path(project_root)
        self.compress_script = self.project_root / ".specify" / "scripts" / "python" / "compress.py"
        
    def intercept_string(self, content: str) -> str:
        """
        Pipes large strings through the isolated uv environment script.
        """
        if len(content) < 2000:
            return content
            
        if not self.compress_script.exists():
            return content
            
        try:
            # Squeeze through the isolated uv environment subprocess
            # capturing strictly the stdout content to replace the original
            proc = subprocess.run(
                ["uv", "run", str(self.compress_script), "--stdin"],
                input=content.encode("utf-8"),
                capture_output=True,
                check=False
            )
            if proc.returncode == 0:
                compressed_stdout = proc.stdout.decode("utf-8")
                if compressed_stdout.strip():
                    return compressed_stdout
            return content
        except Exception:
            return content
