# src/rura_penthe/optimizer/base.py
from abc import ABC, abstractmethod
from typing import List, Dict, Any

class TokenOptimizer(ABC):
    """
    Abstract Base Class defining the payload contract for the middleware.
    """
    
    @abstractmethod
    def optimize_payload(self, messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Takes the heavy messages list generated by spec-kit and compresses it.
        """
        pass

class ContextCompressor(ABC):
    """
    Compresses specific parts of the message (e.g., removing redundant CoT).
    """
    
    @abstractmethod
    def compress(self, content: str) -> str:
        """
        Strips redundant instructions, minimizes metadata, and optimizes text.
        """
        pass

class InterceptorMiddleware:
    """
    The orchestrator that sits between the prompt generation and the API dispatch.
    """
    def __init__(self, optimizer: TokenOptimizer, llm_client: Any):
        self.optimizer = optimizer
        self.llm_client = llm_client

    def chat_completion(self, messages: List[Dict[str, Any]], **kwargs) -> Any:
        # 1. Intercept and Compress
        optimized_messages = self.optimizer.optimize_payload(messages)
        
        # 2. Forward to LLM API
        response = self.llm_client.chat_completion(messages=optimized_messages, **kwargs)
        
        # 3. Post-process (optional: map LLM response back if needed)
        return response
